using System.Text;

namespace Metadata.Design.Generator;

internal static class SourceTextHelper
{
    public static void WriteAutoGeneratedHeader(StringBuilder builder)
    {
        builder.AppendLine(@"//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------");
        builder.AppendLine();
    }
}
