//HintName: MaterialConfigurer.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
// File: 
// 15,4
// </auto-generated>
//----------------------
using MetaModels.Entities;
using Test;

namespace Test
{
    public partial class MaterialConfigurer
        : IObjectMetadataConfigurer<MaterialMetadata>
    {
    }
}
