//HintName: MaterialMetadata.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

using MetaModels.Entities;

namespace Test
{
    public sealed class MaterialMetadata
        : ObjectMetadata
    {
        public global::MetaModels.Entities.PropertyMetadata<string> Code => MaterialConfigurer.Code;
        public global::MetaModels.Entities.PropertyMetadata<string> Name => MaterialConfigurer.Name;
        public global::MetaModels.Entities.PropertyMetadata<global::System.Guid> MasterUnit => MaterialConfigurer.MasterUnit;
    }
}
